### ISSUE TITLE
plugin install error

### ISSUE THREAD

**Issue by fangxu** [AliyunContainerService/helm-acr#12]
helm plugin install https://github.com/AliyunContainerService/helm-acr

> Downloading and installing helm-acr v0.8.1 ...
https://github.com/AliyunContainerService/helm-acr/releases/download/v0.8.1/helm-acr_0.8.1_linux_amd64.tar.gz
mv: cannot stat 'releases/v0.8.1/bin/helm-cm-push': No such file or directory
mv: cannot stat 'releases/v0.8.1/bin/helm-cm-push.exe': No such file or directory
Error: plugin install hook for "cm-push" exited with error

**Comment by xiechengsheng** [comment]
We have updated the plugin with "helm cm-push", please try again
